create extension if not exists vector with schema public

create table "public"."data_source" (
    id bigserial primary key,
    source_link text not null unique,
    source_type text not null
)

create table "public"."content" (
    id bigserial primary key,
    data_source_id bigint not null references public.data_source on delete cascade,
    content text,
    token_count int,
    embedding vector(1536)
)

create table
  public.project (
    id bigint generated by default as identity not null,
    name character varying not null,
    owner_id text null,
    status varchar,
    created_at timestamp with time zone not null default (now() at time zone 'utc'::text),
    updated_at timestamp with time zone not null default (now() at time zone 'utc'::text),
    constraint project_pkey primary key (id)
  ) tablespace pg_default;

create trigger handle_updated_at before
update on project for each row
execute function moddatetime ('updated_at');
project(projectId, name, owner_id, status=IN_PROGRESS)

create table public.source_metadata (
    id bigint generated by default as identity not null,
    project_id bigint,
    type varchar,
    path varchar,
    metadata json
)